import type { ActiveLocale } from "@/config/locales";

export interface ContactContent {
 // Page header
 eyebrow: string;
 title: string;
 description: string;
 // Info cards
 emailLabel: string;
 phoneLabel: string;
 responseLabel: string;
 responseValue: string;
 note: string;
 // Form labels
 labelFullName: string;
 labelEmail: string;
 labelPrefix: string;
 labelPhone: string;
 labelMunicipality: string;
 labelMessage: string;
 // Placeholders
 placeholderFullName: string;
 placeholderEmail: string;
 placeholderPhone: string;
 placeholderMunicipality: string;
 placeholderMessage: string;
 // Consent
 consentText: string;
 consentLinkText: string;
 // Buttons
 submitLabel: string;
 sendingLabel: string;
 // Success
 successTitle: string;
 successBody: string;
 // Error
 submitError: string;
 // Validation errors
 errFullNameRequired: string;
 errFullNameMax: string;
 errEmailRequired: string;
 errEmailInvalid: string;
 errPrefixRequired: string;
 errPhoneRequired: string;
 errPhoneDigits: string;
 errPhoneLength: string;
 errMunicipalityRequired: string;
 errMunicipalityMax: string;
 errMessageRequired: string;
 errMessageMax: string;
 errConsentRequired: string;
 // Metadata
 metaTitle: string;
 metaDescription: string;
}

const content: Record<ActiveLocale, ContactContent> = {
 pt: {
 eyebrow: "CONTACTO",
 title: "Fale connosco",
 description: "Se precisar de uma inspeção independente, de um esclarecimento editorial ou de uma consulta inicial, pode escrever-nos aqui.",
 emailLabel: "Email",
 phoneLabel: "Telefone",
 responseLabel: "Tempo de resposta",
 responseValue: "Em 1 2 dias úteis",
 note: "MoldCheck.pt é uma publicação editorial independente. Não vendemos tratamentos nem recebemos comissões de empresas de remediação.",
 labelFullName: "Nome completo",
 labelEmail: "Email",
 labelPrefix: "Prefixo",
 labelPhone: "Telefone",
 labelMunicipality: "Município",
 labelMessage: "Mensagem",
 placeholderFullName: "O seu nome",
 placeholderEmail: "o.seu@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lisboa, Porto…",
 placeholderMessage: "Diga-nos como podemos ajudar…",
 consentText: "Li e aceito a ",
 consentLinkText: "política de privacidade",
 submitLabel: "Enviar mensagem",
 sendingLabel: "A enviar…",
 successTitle: "Mensagem enviada com sucesso.",
 successBody: "Entraremos em contacto em breve.",
 submitError: "Ocorreu um erro. Por favor, tente novamente.",
 errFullNameRequired: "O nome é obrigatório.",
 errFullNameMax: "Máximo 50 caracteres.",
 errEmailRequired: "O email é obrigatório.",
 errEmailInvalid: "Introduza um email válido.",
 errPrefixRequired: "Selecione um prefixo.",
 errPhoneRequired: "O telefone é obrigatório.",
 errPhoneDigits: "Apenas são permitidos dígitos.",
 errPhoneLength: "Comprimento de telefone inválido.",
 errMunicipalityRequired: "O município é obrigatório.",
 errMunicipalityMax: "Máximo 100 caracteres.",
 errMessageRequired: "A mensagem é obrigatória.",
 errMessageMax: "Máximo 500 caracteres.",
 errConsentRequired: "Deve aceitar a política de privacidade.",
 metaTitle: "Contacto MoldCheck.pt",
 metaDescription: "Contacte o MoldCheck.pt para consultas sobre inspeção independente de humidade e bolor.",
 },
 en: {
 eyebrow: "CONTACT",
 title: "Contact us",
 description: "If you need an independent inspection, an editorial clarification, or an initial consultation, you can write to us here.",
 emailLabel: "Email",
 phoneLabel: "Phone",
 responseLabel: "Response time",
 responseValue: "Within 1 2 business days",
 note: "MoldCheck.pt is an independent editorial publication. We do not sell treatments or take commissions from remediation companies.",
 labelFullName: "Full name",
 labelEmail: "Email",
 labelPrefix: "Prefix",
 labelPhone: "Phone",
 labelMunicipality: "Municipality",
 labelMessage: "Message",
 placeholderFullName: "Your name",
 placeholderEmail: "your@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lisbon, Porto…",
 placeholderMessage: "Tell us how we can help…",
 consentText: "I have read and accept the ",
 consentLinkText: "privacy policy",
 submitLabel: "Send message",
 sendingLabel: "Sending…",
 successTitle: "Message sent successfully.",
 successBody: "We will get back to you shortly.",
 submitError: "An error occurred. Please try again.",
 errFullNameRequired: "Name is required.",
 errFullNameMax: "Maximum 50 characters.",
 errEmailRequired: "Email is required.",
 errEmailInvalid: "Please enter a valid email.",
 errPrefixRequired: "Please select a prefix.",
 errPhoneRequired: "Phone is required.",
 errPhoneDigits: "Only digits are allowed.",
 errPhoneLength: "Invalid phone length.",
 errMunicipalityRequired: "Municipality is required.",
 errMunicipalityMax: "Maximum 100 characters.",
 errMessageRequired: "Message is required.",
 errMessageMax: "Maximum 500 characters.",
 errConsentRequired: "You must accept the privacy policy.",
 metaTitle: "Contact MoldCheck.pt",
 metaDescription: "Contact MoldCheck.pt for enquiries about independent damp and mold inspection.",
 },
 fr: {
 eyebrow: "CONTACT",
 title: "Contactez-nous",
 description: "Si vous avez besoin d'une inspection indépendante, d'une clarification éditoriale ou d'une consultation initiale, vous pouvez nous écrire ici.",
 emailLabel: "Email",
 phoneLabel: "Téléphone",
 responseLabel: "Délai de réponse",
 responseValue: "Sous 1 2 jours ouvrables",
 note: "MoldCheck.pt est une publication éditoriale indépendante. Nous ne vendons pas de traitements et ne percevons pas de commissions d'entreprises de remédiation.",
 labelFullName: "Nom complet",
 labelEmail: "Email",
 labelPrefix: "Indicatif",
 labelPhone: "Téléphone",
 labelMunicipality: "Commune",
 labelMessage: "Message",
 placeholderFullName: "Votre nom",
 placeholderEmail: "votre@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lisbonne, Porto…",
 placeholderMessage: "Dites-nous comment nous pouvons vous aider…",
 consentText: "J'ai lu et j'accepte la ",
 consentLinkText: "politique de confidentialité",
 submitLabel: "Envoyer le message",
 sendingLabel: "Envoi en cours…",
 successTitle: "Message envoyé avec succès.",
 successBody: "Nous vous répondrons dans les plus brefs délais.",
 submitError: "Une erreur s'est produite. Veuillez réessayer.",
 errFullNameRequired: "Le nom est obligatoire.",
 errFullNameMax: "Maximum 50 caractères.",
 errEmailRequired: "L'email est obligatoire.",
 errEmailInvalid: "Veuillez saisir un email valide.",
 errPrefixRequired: "Veuillez sélectionner un indicatif.",
 errPhoneRequired: "Le téléphone est obligatoire.",
 errPhoneDigits: "Seuls les chiffres sont autorisés.",
 errPhoneLength: "Longueur de téléphone invalide.",
 errMunicipalityRequired: "La commune est obligatoire.",
 errMunicipalityMax: "Maximum 100 caractères.",
 errMessageRequired: "Le message est obligatoire.",
 errMessageMax: "Maximum 500 caractères.",
 errConsentRequired: "Vous devez accepter la politique de confidentialité.",
 metaTitle: "Contact MoldCheck.pt",
 metaDescription: "Contactez MoldCheck.pt pour des questions sur l'inspection indépendante de l'humidité et des moisissures.",
 },
 de: {
 eyebrow: "KONTAKT",
 title: "Kontaktieren Sie uns",
 description: "Wenn Sie eine unabhängige Inspektion, eine redaktionelle Klärung oder eine erste Beratung benötigen, können Sie uns hier schreiben.",
 emailLabel: "E-Mail",
 phoneLabel: "Telefon",
 responseLabel: "Antwortzeit",
 responseValue: "Innerhalb von 1 2 Werktagen",
 note: "MoldCheck.pt ist eine unabhängige redaktionelle Publikation. Wir verkaufen keine Behandlungen und erhalten keine Provisionen von Sanierungsunternehmen.",
 labelFullName: "Vollständiger Name",
 labelEmail: "E-Mail",
 labelPrefix: "Vorwahl",
 labelPhone: "Telefon",
 labelMunicipality: "Gemeinde",
 labelMessage: "Nachricht",
 placeholderFullName: "Ihr Name",
 placeholderEmail: "ihre@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lissabon, Porto…",
 placeholderMessage: "Sagen Sie uns, wie wir helfen können…",
 consentText: "Ich habe die ",
 consentLinkText: "Datenschutzerklärung",
 submitLabel: "Nachricht senden",
 sendingLabel: "Wird gesendet…",
 successTitle: "Nachricht erfolgreich gesendet.",
 successBody: "Wir werden uns in Kürze bei Ihnen melden.",
 submitError: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
 errFullNameRequired: "Name ist erforderlich.",
 errFullNameMax: "Maximal 50 Zeichen.",
 errEmailRequired: "E-Mail ist erforderlich.",
 errEmailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
 errPrefixRequired: "Bitte wählen Sie eine Vorwahl.",
 errPhoneRequired: "Telefon ist erforderlich.",
 errPhoneDigits: "Nur Ziffern sind erlaubt.",
 errPhoneLength: "Ungültige Telefonnummer.",
 errMunicipalityRequired: "Gemeinde ist erforderlich.",
 errMunicipalityMax: "Maximal 100 Zeichen.",
 errMessageRequired: "Nachricht ist erforderlich.",
 errMessageMax: "Maximal 500 Zeichen.",
 errConsentRequired: "Sie müssen die Datenschutzerklärung akzeptieren.",
 metaTitle: "Kontakt MoldCheck.pt",
 metaDescription: "Kontaktieren Sie MoldCheck.pt für Anfragen zur unabhängigen Feuchtigkeits- und Schimmelinspektion.",
 },
 nl: {
 eyebrow: "CONTACT",
 title: "Neem contact op",
 description: "Als je een onafhankelijke inspectie, een redactionele verduidelijking of een eerste advies nodig hebt, kun je ons hier schrijven.",
 emailLabel: "E-mail",
 phoneLabel: "Telefoon",
 responseLabel: "Reactietijd",
 responseValue: "Binnen 1 2 werkdagen",
 note: "MoldCheck.pt is een onafhankelijke redactionele publicatie. We verkopen geen behandelingen en ontvangen geen commissies van saneringsbedrijven.",
 labelFullName: "Volledige naam",
 labelEmail: "E-mail",
 labelPrefix: "Landcode",
 labelPhone: "Telefoon",
 labelMunicipality: "Gemeente",
 labelMessage: "Bericht",
 placeholderFullName: "Jouw naam",
 placeholderEmail: "jouw@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lissabon, Porto…",
 placeholderMessage: "Vertel ons hoe we kunnen helpen…",
 consentText: "Ik heb het ",
 consentLinkText: "privacybeleid",
 submitLabel: "Bericht versturen",
 sendingLabel: "Verzenden…",
 successTitle: "Bericht succesvol verzonden.",
 successBody: "We nemen zo snel mogelijk contact met je op.",
 submitError: "Er is een fout opgetreden. Probeer het opnieuw.",
 errFullNameRequired: "Naam is verplicht.",
 errFullNameMax: "Maximaal 50 tekens.",
 errEmailRequired: "E-mail is verplicht.",
 errEmailInvalid: "Voer een geldig e-mailadres in.",
 errPrefixRequired: "Selecteer een landcode.",
 errPhoneRequired: "Telefoon is verplicht.",
 errPhoneDigits: "Alleen cijfers zijn toegestaan.",
 errPhoneLength: "Ongeldig telefoonnummer.",
 errMunicipalityRequired: "Gemeente is verplicht.",
 errMunicipalityMax: "Maximaal 100 tekens.",
 errMessageRequired: "Bericht is verplicht.",
 errMessageMax: "Maximaal 500 tekens.",
 errConsentRequired: "Je moet het privacybeleid accepteren.",
 metaTitle: "Contact MoldCheck.pt",
 metaDescription: "Neem contact op met MoldCheck.pt voor vragen over onafhankelijke vocht- en schimmelinspectie.",
 },
 it: {
 eyebrow: "CONTATTI",
 title: "Contattaci",
 description: "Se hai bisogno di un'ispezione indipendente, di un chiarimento editoriale o di una consulenza iniziale, puoi scriverci qui.",
 emailLabel: "Email",
 phoneLabel: "Telefono",
 responseLabel: "Tempo di risposta",
 responseValue: "Entro 1 2 giorni lavorativi",
 note: "MoldCheck.pt è una pubblicazione editoriale indipendente. Non vendiamo trattamenti né riceviamo commissioni da aziende di risanamento.",
 labelFullName: "Nome completo",
 labelEmail: "Email",
 labelPrefix: "Prefisso",
 labelPhone: "Telefono",
 labelMunicipality: "Comune",
 labelMessage: "Messaggio",
 placeholderFullName: "Il tuo nome",
 placeholderEmail: "tua@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lisbona, Porto…",
 placeholderMessage: "Dicci come possiamo aiutarti…",
 consentText: "Ho letto e accetto la ",
 consentLinkText: "informativa sulla privacy",
 submitLabel: "Invia messaggio",
 sendingLabel: "Invio in corso…",
 successTitle: "Messaggio inviato con successo.",
 successBody: "Ti risponderemo al più presto.",
 submitError: "Si è verificato un errore. Riprova.",
 errFullNameRequired: "Il nome è obbligatorio.",
 errFullNameMax: "Massimo 50 caratteri.",
 errEmailRequired: "L'email è obbligatoria.",
 errEmailInvalid: "Inserisci un'email valida.",
 errPrefixRequired: "Seleziona un prefisso.",
 errPhoneRequired: "Il telefono è obbligatorio.",
 errPhoneDigits: "Sono consentite solo cifre.",
 errPhoneLength: "Lunghezza del numero di telefono non valida.",
 errMunicipalityRequired: "Il comune è obbligatorio.",
 errMunicipalityMax: "Massimo 100 caratteri.",
 errMessageRequired: "Il messaggio è obbligatorio.",
 errMessageMax: "Massimo 500 caratteri.",
 errConsentRequired: "Devi accettare l'informativa sulla privacy.",
 metaTitle: "Contatti MoldCheck.pt",
 metaDescription: "Contatta MoldCheck.pt per consulenze sull'ispezione indipendente di umidità e muffa.",
 },
 es: {
 eyebrow: "CONTACTO",
 title: "Contacta con nosotros",
 description: "Si necesitas una inspección independiente, una aclaración editorial o una consulta inicial, puedes escribirnos aquí.",
 emailLabel: "Email",
 phoneLabel: "Teléfono",
 responseLabel: "Tiempo de respuesta",
 responseValue: "En 1 2 días hábiles",
 note: "MoldCheck.pt es una publicación editorial independiente. No vendemos tratamientos ni cobramos comisiones de empresas de remediación.",
 labelFullName: "Nombre completo",
 labelEmail: "Email",
 labelPrefix: "Prefijo",
 labelPhone: "Teléfono",
 labelMunicipality: "Municipio",
 labelMessage: "Mensaje",
 placeholderFullName: "Tu nombre",
 placeholderEmail: "tu@email.com",
 placeholderPhone: "912 345 678",
 placeholderMunicipality: "Lisboa, Porto…",
 placeholderMessage: "Cuéntanos en qué podemos ayudarte…",
 consentText: "He leído y acepto la ",
 consentLinkText: "política de privacidad",
 submitLabel: "Enviar mensaje",
 sendingLabel: "Enviando…",
 successTitle: "Mensaje enviado correctamente.",
 successBody: "Nos pondremos en contacto contigo en breve.",
 submitError: "Ha ocurrido un error. Por favor, inténtalo de nuevo.",
 errFullNameRequired: "El nombre es obligatorio.",
 errFullNameMax: "Máximo 50 caracteres.",
 errEmailRequired: "El email es obligatorio.",
 errEmailInvalid: "Introduce un email válido.",
 errPrefixRequired: "Selecciona un prefijo.",
 errPhoneRequired: "El teléfono es obligatorio.",
 errPhoneDigits: "Solo se permiten dígitos.",
 errPhoneLength: "Longitud de teléfono no válida.",
 errMunicipalityRequired: "El municipio es obligatorio.",
 errMunicipalityMax: "Máximo 100 caracteres.",
 errMessageRequired: "El mensaje es obligatorio.",
 errMessageMax: "Máximo 500 caracteres.",
 errConsentRequired: "Debes aceptar la política de privacidad.",
 metaTitle: "Contacto MoldCheck.pt",
 metaDescription: "Contacta con MoldCheck.pt para consultas sobre inspección independiente de humedad y moho.",
 },
};

export function getContactContent(locale: ActiveLocale): ContactContent {
 return content[locale] ?? content.en;
}
