module.exports = [
"[project]/.next-internal/server/app/(site)/[locale]/contact/page/actions.js [app-rsc] (server actions loader, ecmascript)", ((__turbopack_context__, module, exports) => {

}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/(site)/[locale]/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/(site)/[locale]/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/features/contact/ContactForm.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "ContactForm",
    ()=>ContactForm
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ContactForm = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ContactForm() from the server but ContactForm is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/features/contact/ContactForm.tsx <module evaluation>", "ContactForm");
}),
"[project]/src/features/contact/ContactForm.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "ContactForm",
    ()=>ContactForm
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ContactForm = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ContactForm() from the server but ContactForm is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/features/contact/ContactForm.tsx", "ContactForm");
}),
"[project]/src/features/contact/ContactForm.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$ContactForm$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/features/contact/ContactForm.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$ContactForm$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/features/contact/ContactForm.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$ContactForm$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/features/contact/contactContent.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getContactContent",
    ()=>getContactContent
]);
const content = {
    pt: {
        eyebrow: "CONTACTO",
        title: "Fale connosco",
        description: "Se precisar de uma inspeção independente, de um esclarecimento editorial ou de uma consulta inicial, pode escrever-nos aqui.",
        emailLabel: "Email",
        phoneLabel: "Telefone",
        responseLabel: "Tempo de resposta",
        responseValue: "Em 1–2 dias úteis",
        note: "MoldCheck.pt é uma publicação editorial independente. Não vendemos tratamentos nem recebemos comissões de empresas de remediação.",
        labelFullName: "Nome completo",
        labelEmail: "Email",
        labelPrefix: "Prefixo",
        labelPhone: "Telefone",
        labelMunicipality: "Município",
        labelMessage: "Mensagem",
        placeholderFullName: "O seu nome",
        placeholderEmail: "o.seu@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lisboa, Porto…",
        placeholderMessage: "Diga-nos como podemos ajudar…",
        consentText: "Li e aceito a ",
        consentLinkText: "política de privacidade",
        submitLabel: "Enviar mensagem",
        sendingLabel: "A enviar…",
        successTitle: "Mensagem enviada com sucesso.",
        successBody: "Entraremos em contacto em breve.",
        submitError: "Ocorreu um erro. Por favor, tente novamente.",
        errFullNameRequired: "O nome é obrigatório.",
        errFullNameMax: "Máximo 50 caracteres.",
        errEmailRequired: "O email é obrigatório.",
        errEmailInvalid: "Introduza um email válido.",
        errPrefixRequired: "Selecione um prefixo.",
        errPhoneRequired: "O telefone é obrigatório.",
        errPhoneDigits: "Apenas são permitidos dígitos.",
        errPhoneLength: "Comprimento de telefone inválido.",
        errMunicipalityRequired: "O município é obrigatório.",
        errMunicipalityMax: "Máximo 100 caracteres.",
        errMessageRequired: "A mensagem é obrigatória.",
        errMessageMax: "Máximo 500 caracteres.",
        errConsentRequired: "Deve aceitar a política de privacidade.",
        metaTitle: "Contacto — MoldCheck.pt",
        metaDescription: "Contacte o MoldCheck.pt para consultas sobre inspeção independente de humidade e bolor."
    },
    en: {
        eyebrow: "CONTACT",
        title: "Contact us",
        description: "If you need an independent inspection, an editorial clarification, or an initial consultation, you can write to us here.",
        emailLabel: "Email",
        phoneLabel: "Phone",
        responseLabel: "Response time",
        responseValue: "Within 1–2 business days",
        note: "MoldCheck.pt is an independent editorial publication. We do not sell treatments or take commissions from remediation companies.",
        labelFullName: "Full name",
        labelEmail: "Email",
        labelPrefix: "Prefix",
        labelPhone: "Phone",
        labelMunicipality: "Municipality",
        labelMessage: "Message",
        placeholderFullName: "Your name",
        placeholderEmail: "your@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lisbon, Porto…",
        placeholderMessage: "Tell us how we can help…",
        consentText: "I have read and accept the ",
        consentLinkText: "privacy policy",
        submitLabel: "Send message",
        sendingLabel: "Sending…",
        successTitle: "Message sent successfully.",
        successBody: "We will get back to you shortly.",
        submitError: "An error occurred. Please try again.",
        errFullNameRequired: "Name is required.",
        errFullNameMax: "Maximum 50 characters.",
        errEmailRequired: "Email is required.",
        errEmailInvalid: "Please enter a valid email.",
        errPrefixRequired: "Please select a prefix.",
        errPhoneRequired: "Phone is required.",
        errPhoneDigits: "Only digits are allowed.",
        errPhoneLength: "Invalid phone length.",
        errMunicipalityRequired: "Municipality is required.",
        errMunicipalityMax: "Maximum 100 characters.",
        errMessageRequired: "Message is required.",
        errMessageMax: "Maximum 500 characters.",
        errConsentRequired: "You must accept the privacy policy.",
        metaTitle: "Contact — MoldCheck.pt",
        metaDescription: "Contact MoldCheck.pt for enquiries about independent damp and mold inspection."
    },
    fr: {
        eyebrow: "CONTACT",
        title: "Contactez-nous",
        description: "Si vous avez besoin d'une inspection indépendante, d'une clarification éditoriale ou d'une consultation initiale, vous pouvez nous écrire ici.",
        emailLabel: "Email",
        phoneLabel: "Téléphone",
        responseLabel: "Délai de réponse",
        responseValue: "Sous 1–2 jours ouvrables",
        note: "MoldCheck.pt est une publication éditoriale indépendante. Nous ne vendons pas de traitements et ne percevons pas de commissions d'entreprises de remédiation.",
        labelFullName: "Nom complet",
        labelEmail: "Email",
        labelPrefix: "Indicatif",
        labelPhone: "Téléphone",
        labelMunicipality: "Commune",
        labelMessage: "Message",
        placeholderFullName: "Votre nom",
        placeholderEmail: "votre@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lisbonne, Porto…",
        placeholderMessage: "Dites-nous comment nous pouvons vous aider…",
        consentText: "J'ai lu et j'accepte la ",
        consentLinkText: "politique de confidentialité",
        submitLabel: "Envoyer le message",
        sendingLabel: "Envoi en cours…",
        successTitle: "Message envoyé avec succès.",
        successBody: "Nous vous répondrons dans les plus brefs délais.",
        submitError: "Une erreur s'est produite. Veuillez réessayer.",
        errFullNameRequired: "Le nom est obligatoire.",
        errFullNameMax: "Maximum 50 caractères.",
        errEmailRequired: "L'email est obligatoire.",
        errEmailInvalid: "Veuillez saisir un email valide.",
        errPrefixRequired: "Veuillez sélectionner un indicatif.",
        errPhoneRequired: "Le téléphone est obligatoire.",
        errPhoneDigits: "Seuls les chiffres sont autorisés.",
        errPhoneLength: "Longueur de téléphone invalide.",
        errMunicipalityRequired: "La commune est obligatoire.",
        errMunicipalityMax: "Maximum 100 caractères.",
        errMessageRequired: "Le message est obligatoire.",
        errMessageMax: "Maximum 500 caractères.",
        errConsentRequired: "Vous devez accepter la politique de confidentialité.",
        metaTitle: "Contact — MoldCheck.pt",
        metaDescription: "Contactez MoldCheck.pt pour des questions sur l'inspection indépendante de l'humidité et des moisissures."
    },
    de: {
        eyebrow: "KONTAKT",
        title: "Kontaktieren Sie uns",
        description: "Wenn Sie eine unabhängige Inspektion, eine redaktionelle Klärung oder eine erste Beratung benötigen, können Sie uns hier schreiben.",
        emailLabel: "E-Mail",
        phoneLabel: "Telefon",
        responseLabel: "Antwortzeit",
        responseValue: "Innerhalb von 1–2 Werktagen",
        note: "MoldCheck.pt ist eine unabhängige redaktionelle Publikation. Wir verkaufen keine Behandlungen und erhalten keine Provisionen von Sanierungsunternehmen.",
        labelFullName: "Vollständiger Name",
        labelEmail: "E-Mail",
        labelPrefix: "Vorwahl",
        labelPhone: "Telefon",
        labelMunicipality: "Gemeinde",
        labelMessage: "Nachricht",
        placeholderFullName: "Ihr Name",
        placeholderEmail: "ihre@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lissabon, Porto…",
        placeholderMessage: "Sagen Sie uns, wie wir helfen können…",
        consentText: "Ich habe die ",
        consentLinkText: "Datenschutzerklärung",
        submitLabel: "Nachricht senden",
        sendingLabel: "Wird gesendet…",
        successTitle: "Nachricht erfolgreich gesendet.",
        successBody: "Wir werden uns in Kürze bei Ihnen melden.",
        submitError: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
        errFullNameRequired: "Name ist erforderlich.",
        errFullNameMax: "Maximal 50 Zeichen.",
        errEmailRequired: "E-Mail ist erforderlich.",
        errEmailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
        errPrefixRequired: "Bitte wählen Sie eine Vorwahl.",
        errPhoneRequired: "Telefon ist erforderlich.",
        errPhoneDigits: "Nur Ziffern sind erlaubt.",
        errPhoneLength: "Ungültige Telefonnummer.",
        errMunicipalityRequired: "Gemeinde ist erforderlich.",
        errMunicipalityMax: "Maximal 100 Zeichen.",
        errMessageRequired: "Nachricht ist erforderlich.",
        errMessageMax: "Maximal 500 Zeichen.",
        errConsentRequired: "Sie müssen die Datenschutzerklärung akzeptieren.",
        metaTitle: "Kontakt — MoldCheck.pt",
        metaDescription: "Kontaktieren Sie MoldCheck.pt für Anfragen zur unabhängigen Feuchtigkeits- und Schimmelinspektion."
    },
    nl: {
        eyebrow: "CONTACT",
        title: "Neem contact op",
        description: "Als je een onafhankelijke inspectie, een redactionele verduidelijking of een eerste advies nodig hebt, kun je ons hier schrijven.",
        emailLabel: "E-mail",
        phoneLabel: "Telefoon",
        responseLabel: "Reactietijd",
        responseValue: "Binnen 1–2 werkdagen",
        note: "MoldCheck.pt is een onafhankelijke redactionele publicatie. We verkopen geen behandelingen en ontvangen geen commissies van saneringsbedrijven.",
        labelFullName: "Volledige naam",
        labelEmail: "E-mail",
        labelPrefix: "Landcode",
        labelPhone: "Telefoon",
        labelMunicipality: "Gemeente",
        labelMessage: "Bericht",
        placeholderFullName: "Jouw naam",
        placeholderEmail: "jouw@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lissabon, Porto…",
        placeholderMessage: "Vertel ons hoe we kunnen helpen…",
        consentText: "Ik heb het ",
        consentLinkText: "privacybeleid",
        submitLabel: "Bericht versturen",
        sendingLabel: "Verzenden…",
        successTitle: "Bericht succesvol verzonden.",
        successBody: "We nemen zo snel mogelijk contact met je op.",
        submitError: "Er is een fout opgetreden. Probeer het opnieuw.",
        errFullNameRequired: "Naam is verplicht.",
        errFullNameMax: "Maximaal 50 tekens.",
        errEmailRequired: "E-mail is verplicht.",
        errEmailInvalid: "Voer een geldig e-mailadres in.",
        errPrefixRequired: "Selecteer een landcode.",
        errPhoneRequired: "Telefoon is verplicht.",
        errPhoneDigits: "Alleen cijfers zijn toegestaan.",
        errPhoneLength: "Ongeldig telefoonnummer.",
        errMunicipalityRequired: "Gemeente is verplicht.",
        errMunicipalityMax: "Maximaal 100 tekens.",
        errMessageRequired: "Bericht is verplicht.",
        errMessageMax: "Maximaal 500 tekens.",
        errConsentRequired: "Je moet het privacybeleid accepteren.",
        metaTitle: "Contact — MoldCheck.pt",
        metaDescription: "Neem contact op met MoldCheck.pt voor vragen over onafhankelijke vocht- en schimmelinspectie."
    },
    it: {
        eyebrow: "CONTATTI",
        title: "Contattaci",
        description: "Se hai bisogno di un'ispezione indipendente, di un chiarimento editoriale o di una consulenza iniziale, puoi scriverci qui.",
        emailLabel: "Email",
        phoneLabel: "Telefono",
        responseLabel: "Tempo di risposta",
        responseValue: "Entro 1–2 giorni lavorativi",
        note: "MoldCheck.pt è una pubblicazione editoriale indipendente. Non vendiamo trattamenti né riceviamo commissioni da aziende di risanamento.",
        labelFullName: "Nome completo",
        labelEmail: "Email",
        labelPrefix: "Prefisso",
        labelPhone: "Telefono",
        labelMunicipality: "Comune",
        labelMessage: "Messaggio",
        placeholderFullName: "Il tuo nome",
        placeholderEmail: "tua@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lisbona, Porto…",
        placeholderMessage: "Dicci come possiamo aiutarti…",
        consentText: "Ho letto e accetto la ",
        consentLinkText: "informativa sulla privacy",
        submitLabel: "Invia messaggio",
        sendingLabel: "Invio in corso…",
        successTitle: "Messaggio inviato con successo.",
        successBody: "Ti risponderemo al più presto.",
        submitError: "Si è verificato un errore. Riprova.",
        errFullNameRequired: "Il nome è obbligatorio.",
        errFullNameMax: "Massimo 50 caratteri.",
        errEmailRequired: "L'email è obbligatoria.",
        errEmailInvalid: "Inserisci un'email valida.",
        errPrefixRequired: "Seleziona un prefisso.",
        errPhoneRequired: "Il telefono è obbligatorio.",
        errPhoneDigits: "Sono consentite solo cifre.",
        errPhoneLength: "Lunghezza del numero di telefono non valida.",
        errMunicipalityRequired: "Il comune è obbligatorio.",
        errMunicipalityMax: "Massimo 100 caratteri.",
        errMessageRequired: "Il messaggio è obbligatorio.",
        errMessageMax: "Massimo 500 caratteri.",
        errConsentRequired: "Devi accettare l'informativa sulla privacy.",
        metaTitle: "Contatti — MoldCheck.pt",
        metaDescription: "Contatta MoldCheck.pt per consulenze sull'ispezione indipendente di umidità e muffa."
    },
    es: {
        eyebrow: "CONTACTO",
        title: "Contacta con nosotros",
        description: "Si necesitas una inspección independiente, una aclaración editorial o una consulta inicial, puedes escribirnos aquí.",
        emailLabel: "Email",
        phoneLabel: "Teléfono",
        responseLabel: "Tiempo de respuesta",
        responseValue: "En 1–2 días hábiles",
        note: "MoldCheck.pt es una publicación editorial independiente. No vendemos tratamientos ni cobramos comisiones de empresas de remediación.",
        labelFullName: "Nombre completo",
        labelEmail: "Email",
        labelPrefix: "Prefijo",
        labelPhone: "Teléfono",
        labelMunicipality: "Municipio",
        labelMessage: "Mensaje",
        placeholderFullName: "Tu nombre",
        placeholderEmail: "tu@email.com",
        placeholderPhone: "912 345 678",
        placeholderMunicipality: "Lisboa, Porto…",
        placeholderMessage: "Cuéntanos en qué podemos ayudarte…",
        consentText: "He leído y acepto la ",
        consentLinkText: "política de privacidad",
        submitLabel: "Enviar mensaje",
        sendingLabel: "Enviando…",
        successTitle: "Mensaje enviado correctamente.",
        successBody: "Nos pondremos en contacto contigo en breve.",
        submitError: "Ha ocurrido un error. Por favor, inténtalo de nuevo.",
        errFullNameRequired: "El nombre es obligatorio.",
        errFullNameMax: "Máximo 50 caracteres.",
        errEmailRequired: "El email es obligatorio.",
        errEmailInvalid: "Introduce un email válido.",
        errPrefixRequired: "Selecciona un prefijo.",
        errPhoneRequired: "El teléfono es obligatorio.",
        errPhoneDigits: "Solo se permiten dígitos.",
        errPhoneLength: "Longitud de teléfono no válida.",
        errMunicipalityRequired: "El municipio es obligatorio.",
        errMunicipalityMax: "Máximo 100 caracteres.",
        errMessageRequired: "El mensaje es obligatorio.",
        errMessageMax: "Máximo 500 caracteres.",
        errConsentRequired: "Debes aceptar la política de privacidad.",
        metaTitle: "Contacto — MoldCheck.pt",
        metaDescription: "Contacta con MoldCheck.pt para consultas sobre inspección independiente de humedad y moho."
    }
};
function getContactContent(locale) {
    return content[locale] ?? content.en;
}
}),
"[project]/src/app/(site)/[locale]/contact/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>ContactPage,
    "generateMetadata",
    ()=>generateMetadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$ContactForm$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/features/contact/ContactForm.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$contactContent$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/features/contact/contactContent.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$routing$2f$paths$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/routing/paths.ts [app-rsc] (ecmascript)");
;
;
;
;
async function generateMetadata({ params }) {
    const { locale } = await params;
    const c = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$contactContent$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getContactContent"])(locale);
    return {
        title: c.metaTitle,
        description: c.metaDescription,
        alternates: {
            canonical: `https://moldcheck.pt${(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$routing$2f$paths$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getGlobalPath"])(locale, "contact")}`
        }
    };
}
async function ContactPage({ params }) {
    const { locale } = await params;
    const c = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$contactContent$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getContactContent"])(locale);
    const sourcePage = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$routing$2f$paths$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getGlobalPath"])(locale, "contact");
    const privacyHref = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$routing$2f$paths$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getGlobalPath"])(locale, "privacy");
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
        className: "contact-page",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: "contact-page__inner",
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("header", {
                    className: "contact-page__header",
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                            className: "contact-page__eyebrow",
                            children: c.eyebrow
                        }, void 0, false, {
                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                            lineNumber: 29,
                            columnNumber: 11
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h1", {
                            className: "contact-page__title",
                            children: c.title
                        }, void 0, false, {
                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                            lineNumber: 30,
                            columnNumber: 11
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                            className: "contact-page__description",
                            children: c.description
                        }, void 0, false, {
                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                            lineNumber: 31,
                            columnNumber: 11
                        }, this)
                    ]
                }, void 0, true, {
                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                    lineNumber: 28,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "contact-page__body",
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                            className: "contact-page__form-col",
                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$features$2f$contact$2f$ContactForm$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ContactForm"], {
                                sourcePage: sourcePage,
                                content: c,
                                privacyHref: privacyHref
                            }, void 0, false, {
                                fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                lineNumber: 38,
                                columnNumber: 13
                            }, this)
                        }, void 0, false, {
                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                            lineNumber: 37,
                            columnNumber: 11
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("aside", {
                            className: "contact-page__info-col",
                            children: [
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: "contact-info-card",
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            className: "contact-info-card__icon",
                                            "aria-hidden": "true",
                                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("svg", {
                                                width: "20",
                                                height: "20",
                                                viewBox: "0 0 24 24",
                                                fill: "none",
                                                stroke: "currentColor",
                                                strokeWidth: "1.75",
                                                strokeLinecap: "round",
                                                strokeLinejoin: "round",
                                                children: [
                                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("rect", {
                                                        x: "2",
                                                        y: "4",
                                                        width: "20",
                                                        height: "16",
                                                        rx: "2"
                                                    }, void 0, false, {
                                                        fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                        lineNumber: 46,
                                                        columnNumber: 19
                                                    }, this),
                                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("polyline", {
                                                        points: "2,4 12,13 22,4"
                                                    }, void 0, false, {
                                                        fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                        lineNumber: 47,
                                                        columnNumber: 19
                                                    }, this)
                                                ]
                                            }, void 0, true, {
                                                fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                lineNumber: 45,
                                                columnNumber: 17
                                            }, this)
                                        }, void 0, false, {
                                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                            lineNumber: 44,
                                            columnNumber: 15
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            children: [
                                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                                    className: "contact-info-card__label",
                                                    children: c.emailLabel
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 51,
                                                    columnNumber: 17
                                                }, this),
                                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                                                    href: "mailto:info@moldcheck.pt",
                                                    className: "contact-info-card__value",
                                                    children: "info@moldcheck.pt"
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 52,
                                                    columnNumber: 17
                                                }, this)
                                            ]
                                        }, void 0, true, {
                                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                            lineNumber: 50,
                                            columnNumber: 15
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                    lineNumber: 43,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: "contact-info-card",
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            className: "contact-info-card__icon",
                                            "aria-hidden": "true",
                                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("svg", {
                                                width: "20",
                                                height: "20",
                                                viewBox: "0 0 24 24",
                                                fill: "none",
                                                stroke: "currentColor",
                                                strokeWidth: "1.75",
                                                strokeLinecap: "round",
                                                strokeLinejoin: "round",
                                                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("path", {
                                                    d: "M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 1.27h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 8.91a16 16 0 0 0 6 6l.91-.91a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 59,
                                                    columnNumber: 19
                                                }, this)
                                            }, void 0, false, {
                                                fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                lineNumber: 58,
                                                columnNumber: 17
                                            }, this)
                                        }, void 0, false, {
                                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                            lineNumber: 57,
                                            columnNumber: 15
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            children: [
                                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                                    className: "contact-info-card__label",
                                                    children: c.phoneLabel
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 63,
                                                    columnNumber: 17
                                                }, this),
                                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                                                    href: "tel:+351308801808",
                                                    className: "contact-info-card__value",
                                                    children: "+351 308 801 808"
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 64,
                                                    columnNumber: 17
                                                }, this)
                                            ]
                                        }, void 0, true, {
                                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                            lineNumber: 62,
                                            columnNumber: 15
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                    lineNumber: 56,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: "contact-info-card",
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            className: "contact-info-card__icon",
                                            "aria-hidden": "true",
                                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("svg", {
                                                width: "20",
                                                height: "20",
                                                viewBox: "0 0 24 24",
                                                fill: "none",
                                                stroke: "currentColor",
                                                strokeWidth: "1.75",
                                                strokeLinecap: "round",
                                                strokeLinejoin: "round",
                                                children: [
                                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("circle", {
                                                        cx: "12",
                                                        cy: "12",
                                                        r: "10"
                                                    }, void 0, false, {
                                                        fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                        lineNumber: 71,
                                                        columnNumber: 19
                                                    }, this),
                                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("polyline", {
                                                        points: "12 6 12 12 16 14"
                                                    }, void 0, false, {
                                                        fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                        lineNumber: 72,
                                                        columnNumber: 19
                                                    }, this)
                                                ]
                                            }, void 0, true, {
                                                fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                lineNumber: 70,
                                                columnNumber: 17
                                            }, this)
                                        }, void 0, false, {
                                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                            lineNumber: 69,
                                            columnNumber: 15
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            children: [
                                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                                    className: "contact-info-card__label",
                                                    children: c.responseLabel
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 76,
                                                    columnNumber: 17
                                                }, this),
                                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                                    className: "contact-info-card__value",
                                                    children: c.responseValue
                                                }, void 0, false, {
                                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                                    lineNumber: 77,
                                                    columnNumber: 17
                                                }, this)
                                            ]
                                        }, void 0, true, {
                                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                            lineNumber: 75,
                                            columnNumber: 15
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                    lineNumber: 68,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: "contact-info-note",
                                    children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                        children: c.note
                                    }, void 0, false, {
                                        fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                        lineNumber: 82,
                                        columnNumber: 15
                                    }, this)
                                }, void 0, false, {
                                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                                    lineNumber: 81,
                                    columnNumber: 13
                                }, this)
                            ]
                        }, void 0, true, {
                            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                            lineNumber: 42,
                            columnNumber: 11
                        }, this)
                    ]
                }, void 0, true, {
                    fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
                    lineNumber: 35,
                    columnNumber: 9
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
            lineNumber: 26,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/src/app/(site)/[locale]/contact/page.tsx",
        lineNumber: 25,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/app/(site)/[locale]/contact/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/(site)/[locale]/contact/page.tsx [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__bac75b24._.js.map