// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/about" | "/[locale]/articles" | "/[locale]/articles/[slug]" | "/[locale]/contact" | "/[locale]/editorial-policy" | "/[locale]/health" | "/[locale]/health/[slug]" | "/[locale]/inspection" | "/[locale]/inspection/[slug]" | "/[locale]/mold-types" | "/[locale]/mold-types/[slug]" | "/[locale]/municipalities/[slug]" | "/[locale]/newsletter/unsubscribe" | "/[locale]/portugal" | "/[locale]/privacy" | "/[locale]/remediation" | "/[locale]/remediation/[slug]" | "/[locale]/search" | "/[locale]/services" | "/[locale]/shop" | "/[locale]/shop/thank-you" | "/[locale]/tools" | "/[locale]/tools/[slug]"
type AppRouteHandlerRoutes = "/api/checkout" | "/api/contact" | "/api/newsletter/calculator-completed" | "/api/newsletter/nurture/run" | "/api/newsletter/subscribe" | "/api/newsletter/unsubscribe" | "/api/preview" | "/api/revalidate" | "/api/search" | "/api/tools/[slug]" | "/api/webhooks/stripe"
type PageRoutes = "/_app" | "/_document"
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = "/"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_app": {}
  "/_document": {}
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/articles": { "locale": string; }
  "/[locale]/articles/[slug]": { "locale": string; "slug": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/editorial-policy": { "locale": string; }
  "/[locale]/health": { "locale": string; }
  "/[locale]/health/[slug]": { "locale": string; "slug": string; }
  "/[locale]/inspection": { "locale": string; }
  "/[locale]/inspection/[slug]": { "locale": string; "slug": string; }
  "/[locale]/mold-types": { "locale": string; }
  "/[locale]/mold-types/[slug]": { "locale": string; "slug": string; }
  "/[locale]/municipalities/[slug]": { "locale": string; "slug": string; }
  "/[locale]/newsletter/unsubscribe": { "locale": string; }
  "/[locale]/portugal": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/remediation": { "locale": string; }
  "/[locale]/remediation/[slug]": { "locale": string; "slug": string; }
  "/[locale]/search": { "locale": string; }
  "/[locale]/services": { "locale": string; }
  "/[locale]/shop": { "locale": string; }
  "/[locale]/shop/thank-you": { "locale": string; }
  "/[locale]/tools": { "locale": string; }
  "/[locale]/tools/[slug]": { "locale": string; "slug": string; }
  "/api/checkout": {}
  "/api/contact": {}
  "/api/newsletter/calculator-completed": {}
  "/api/newsletter/nurture/run": {}
  "/api/newsletter/subscribe": {}
  "/api/newsletter/unsubscribe": {}
  "/api/preview": {}
  "/api/revalidate": {}
  "/api/search": {}
  "/api/tools/[slug]": { "slug": string; }
  "/api/webhooks/stripe": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
